"""Markdown export for debate results.

Pure function that converts a ``DebateResult`` dataclass into a
GitHub-flavored Markdown report string. No I/O, no side effects.
"""

from __future__ import annotations

import datetime
import logging
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from options_arena.agents._parsing import DebateResult
    from options_arena.models import AgentResponse, VolatilityThesis

logger = logging.getLogger(__name__)

DISCLAIMER: str = (
    "DISCLAIMER: This analysis is generated by AI for educational and research purposes only. "
    "It does not constitute investment advice, a recommendation, or a solicitation to buy or "
    "sell any securities or options. Options trading involves substantial risk of loss and is "
    "not appropriate for all investors. Past performance and AI-generated analysis do not "
    "guarantee future results. Market data may be delayed or inaccurate. Always consult a "
    "qualified financial advisor before making investment decisions."
)


def _render_agent_section(
    heading: str,
    response: AgentResponse,
    *,
    include_risks: bool = True,
) -> str:
    """Render a bull/bear/rebuttal agent section as Markdown.

    Args:
        heading: Section heading (e.g. "Bull Case", "Bear Case", "Bull Rebuttal").
        response: The agent's structured response.
        include_risks: Whether to render a "Risks Cited" subsection.

    Returns:
        Markdown string for the section.
    """
    lines: list[str] = [
        f"## {heading} (Confidence: {response.confidence:.0%})",
        "",
        response.argument,
        "",
    ]

    if response.key_points:
        lines.append("### Key Points")
        for point in response.key_points:
            lines.append(f"- {point}")
        lines.append("")

    if include_risks and response.risks_cited:
        lines.append("### Risks Cited")
        for risk in response.risks_cited:
            lines.append(f"- {risk}")
        lines.append("")

    return "\n".join(lines)


def _render_vol_section(vol: VolatilityThesis) -> str:
    """Render the volatility assessment section as Markdown.

    Args:
        vol: The volatility thesis from the vol agent.

    Returns:
        Markdown string for the volatility section.
    """
    lines: list[str] = [
        "## Volatility Assessment",
        "",
        (f"**IV Assessment**: {vol.iv_assessment.value} | **Confidence**: {vol.confidence:.0%}"),
        "",
        vol.strategy_rationale,
        "",
    ]

    if vol.key_vol_factors:
        lines.append("### Key Volatility Factors")
        for factor in vol.key_vol_factors:
            lines.append(f"- {factor}")
        lines.append("")

    return "\n".join(lines)


def export_debate_markdown(result: DebateResult) -> str:
    """Convert a debate result into a Markdown report string.

    This is a pure function with no side effects. The caller is responsible
    for writing the returned string to a file or displaying it.

    Args:
        result: Complete debate output from ``run_debate()``.

    Returns:
        A GitHub-flavored Markdown string containing the full report
        with header, agent sections, verdict, and disclaimer.
    """
    now_utc = datetime.datetime.now(datetime.UTC)
    date_str = now_utc.strftime("%Y-%m-%d %H:%M UTC")
    duration_s = result.duration_ms / 1000
    model_name = result.bull_response.model_used
    fallback_str = "Yes" if result.is_fallback else "No"

    sections: list[str] = []

    # --- Header ---
    header_lines: list[str] = [
        f"# Options Arena Debate Report: {result.context.ticker}",
        "",
        (f"**Date**: {date_str} | **Duration**: {duration_s:.1f}s | **Model**: {model_name}"),
        f"**Fallback**: {fallback_str}",
        "",
    ]
    sections.append("\n".join(header_lines))

    # --- Bull Case ---
    sections.append(
        _render_agent_section("Bull Case", result.bull_response),
    )

    # --- Bear Case ---
    sections.append(
        _render_agent_section("Bear Case", result.bear_response),
    )

    # --- Volatility Assessment (optional) ---
    if result.vol_response is not None:
        sections.append(_render_vol_section(result.vol_response))

    # --- Bull Rebuttal (optional) ---
    if result.bull_rebuttal is not None:
        sections.append(
            _render_agent_section(
                "Bull Rebuttal",
                result.bull_rebuttal,
                include_risks=False,
            ),
        )

    # --- Verdict ---
    thesis = result.thesis
    strategy_str = thesis.recommended_strategy.value if thesis.recommended_strategy else "None"
    verdict_lines: list[str] = [
        "## Verdict",
        "",
        (f"**Direction**: {thesis.direction.value} | **Confidence**: {thesis.confidence:.0%}"),
        f"**Strategy**: {strategy_str}",
        "",
        thesis.summary,
        "",
        "### Risk Assessment",
        "",
        thesis.risk_assessment,
        "",
    ]
    sections.append("\n".join(verdict_lines))

    # --- Disclaimer ---
    disclaimer_lines: list[str] = [
        "---",
        "",
        f"*{DISCLAIMER}*",
        "",
    ]
    sections.append("\n".join(disclaimer_lines))

    return "\n".join(sections)


def export_debate_to_file(
    result: DebateResult,
    path: Path,
    fmt: str = "md",
) -> Path:
    """Write debate result to file as markdown or PDF.

    Args:
        result: Complete debate output from ``run_debate()``.
        path: Destination file path.
        fmt: Output format — ``"md"`` (default) or ``"pdf"``.

    Returns:
        The path that was written.

    Raises:
        ValueError: If *fmt* is not ``"md"`` or ``"pdf"``.
        ImportError: If *fmt* is ``"pdf"`` and ``weasyprint`` is not installed.
    """
    md_content = export_debate_markdown(result)
    if fmt == "md":
        path.write_text(md_content, encoding="utf-8")
        return path
    if fmt == "pdf":
        return _render_pdf(md_content, path)
    raise ValueError(f"Unsupported format: {fmt}")


def _render_pdf(md_content: str, path: Path) -> Path:
    """Convert markdown to PDF via weasyprint.

    Wraps the markdown in minimal ``<pre>`` HTML and renders to PDF.

    Args:
        md_content: The markdown string to render.
        path: Destination PDF file path.

    Returns:
        The path that was written.

    Raises:
        ImportError: If ``weasyprint`` is not installed.
    """
    try:
        from weasyprint import HTML  # type: ignore[import-not-found]
    except ImportError:
        raise ImportError(
            "PDF export requires weasyprint. Install: uv add 'options-arena[pdf]'"
        ) from None
    html = f"<html><body><pre>{md_content}</pre></body></html>"
    HTML(string=html).write_pdf(str(path))
    return path
