"""Options Arena — Data Models.

Re-exports all public models and enums from the ``models`` package.
Consumers import from the package: ``from options_arena.models import OptionContract``.
"""

from options_arena.models.analysis import (
    AgencyQuery,
    AgencyResponse,
    AgentPrediction,
    AgentResponse,
    Citation,
    ContractConstraint,
    ContrarianThesis,
    DeskResponse,
    ExtendedTradeThesis,
    FlowThesis,
    FundamentalThesis,
    MarketContext,
    PositionSizeResult,
    QueryIntent,
    RiskAssessment,
    TradeThesis,
    VolatilityThesis,
)
from options_arena.models.analytics import (
    AgentAccuracyReport,
    AgentCalibrationData,
    AgentWeightsComparison,
    CalibrationBucket,
    ContractOutcome,
    DeltaPerformanceResult,
    DrawdownPoint,
    DTEBucketResult,
    EquityCurvePoint,
    GreeksDecompositionResult,
    HoldingPeriodComparison,
    HoldingPeriodResult,
    IndicatorAttributionResult,
    IVRankBucketResult,
    NormalizationStats,
    PerformanceSummary,
    RecommendedContract,
    RiskAdjustedMetrics,
    ScoreCalibrationBucket,
    SectorPerformanceResult,
    WeightSnapshot,
    WinRateResult,
)
from options_arena.models.audit import AuditFinding, AuditLayerSummary, AuditReport
from options_arena.models.config import (
    AgencyConfig,
    AnalyticsConfig,
    AppSettings,
    DataConfig,
    DebateConfig,
    FinancialDatasetsConfig,
    IntelligenceConfig,
    LogConfig,
    MLConfig,
    OpenBBConfig,
    PositionSizingConfig,
    PricingConfig,
    ScanConfig,
    ServiceConfig,
    SpreadConfig,
)
from options_arena.models.correlation import CorrelationMatrix, PairwiseCorrelation
from options_arena.models.enums import (
    INDUSTRY_GROUP_ALIASES,
    SECTOR_ALIASES,
    SECTOR_TO_INDUSTRY_GROUPS,
    TICKER_RE,
    AuditLayer,
    AuditSeverity,
    CatalystImpact,
    ConstraintSeverity,
    ConstraintViolationType,
    DeskType,
    DividendSource,
    ExerciseStyle,
    FredTransform,
    GICSIndustryGroup,
    GICSSector,
    GreeksGroupBy,
    GreeksSource,
    IVTermStructureShape,
    LLMProvider,
    MacdSignal,
    MacroRegime,
    MarketCapTier,
    MarketRegime,
    OptionType,
    OutcomeCollectionMethod,
    PositionSide,
    PricingModel,
    QueryType,
    RiskLevel,
    ScanPreset,
    ScanSource,
    SignalDirection,
    SpreadType,
    SurfaceMethod,
    ValuationSignal,
    VolAssessment,
    VolRegime,
    VolRegimeTier,
    WeightType,
)
from options_arena.models.filters import (
    OptionsFilters,
    ScanFilterSpec,
    ScoringFilters,
    UniverseFilters,
)
from options_arena.models.financial_datasets import (
    BalanceSheetData,
    FinancialDatasetsPackage,
    FinancialMetricsData,
    IncomeStatementData,
)
from options_arena.models.health import HealthStatus
from options_arena.models.history import HistoryPoint, TrendingTicker
from options_arena.models.intelligence import (
    AnalystActivitySnapshot,
    AnalystSnapshot,
    InsiderSnapshot,
    InsiderTransaction,
    InstitutionalSnapshot,
    IntelligencePackage,
    UpgradeDowngrade,
)
from options_arena.models.macro import MacroContext, MacroRegimeResult, MacroSignals
from options_arena.models.market_data import OHLCV, Quote, TickerInfo
from options_arena.models.metadata import MetadataCoverage, TickerMetadata
from options_arena.models.options import (
    OptionContract,
    OptionGreeks,
    OptionSpread,
    SpreadAnalysis,
    SpreadLeg,
)
from options_arena.models.scan import IndicatorSignals, ScanRun, TickerScore
from options_arena.models.scan_delta import ScanDiff, TickerDelta
from options_arena.models.scoring import DimensionalScores, DirectionSignal
from options_arena.models.valuation import CompositeValuation, ValuationModelResult

__all__ = [
    # Enums
    "AuditLayer",
    "AuditSeverity",
    "CatalystImpact",
    "ConstraintSeverity",
    "ConstraintViolationType",
    "DeskType",
    "DividendSource",
    "ExerciseStyle",
    "GICSIndustryGroup",
    "GICSSector",
    "GreeksGroupBy",
    "FredTransform",
    "GreeksSource",
    "INDUSTRY_GROUP_ALIASES",
    "IVTermStructureShape",
    "LLMProvider",
    "MacdSignal",
    "MacroRegime",
    "MarketCapTier",
    "MarketRegime",
    "OptionType",
    "OutcomeCollectionMethod",
    "PositionSide",
    "PricingModel",
    "QueryType",
    "RiskLevel",
    "SECTOR_ALIASES",
    "SECTOR_TO_INDUSTRY_GROUPS",
    "ScanPreset",
    "ScanSource",
    "SignalDirection",
    "SpreadType",
    "SurfaceMethod",
    "ValuationSignal",
    "VolAssessment",
    "VolRegime",
    "VolRegimeTier",
    "WeightType",
    # Market data
    "OHLCV",
    "Quote",
    "TickerInfo",
    # Options
    "OptionContract",
    "OptionGreeks",
    "OptionSpread",
    "SpreadAnalysis",
    "SpreadLeg",
    # Analysis
    "AgencyQuery",
    "AgencyResponse",
    "AgentPrediction",
    "AgentResponse",
    "Citation",
    "ContractConstraint",
    "ContrarianThesis",
    "DeskResponse",
    "ExtendedTradeThesis",
    "FlowThesis",
    "FundamentalThesis",
    "MarketContext",
    "PositionSizeResult",
    "QueryIntent",
    "RiskAssessment",
    "TradeThesis",
    "VolatilityThesis",
    # Analytics
    "AgentAccuracyReport",
    "AgentCalibrationData",
    "AgentWeightsComparison",
    "CalibrationBucket",
    "ContractOutcome",
    "DTEBucketResult",
    "DeltaPerformanceResult",
    "DrawdownPoint",
    "EquityCurvePoint",
    "GreeksDecompositionResult",
    "HoldingPeriodComparison",
    "HoldingPeriodResult",
    "IVRankBucketResult",
    "IndicatorAttributionResult",
    "NormalizationStats",
    "PerformanceSummary",
    "RecommendedContract",
    "RiskAdjustedMetrics",
    "ScoreCalibrationBucket",
    "SectorPerformanceResult",
    "WeightSnapshot",
    "WinRateResult",
    # Scan
    "IndicatorSignals",
    "ScanRun",
    "TickerScore",
    # Scan delta
    "ScanDiff",
    "TickerDelta",
    # Scoring
    "DimensionalScores",
    "DirectionSignal",
    # Macro
    "MacroContext",
    "MacroRegimeResult",
    "MacroSignals",
    # Config
    "AgencyConfig",
    "AnalyticsConfig",
    "AppSettings",
    "DataConfig",
    "DebateConfig",
    "FinancialDatasetsConfig",
    "IntelligenceConfig",
    "LogConfig",
    "MLConfig",
    "OpenBBConfig",
    "PositionSizingConfig",
    "PricingConfig",
    "ScanConfig",
    "ServiceConfig",
    "SpreadConfig",
    "TICKER_RE",
    # Filters
    "OptionsFilters",
    "ScanFilterSpec",
    "ScoringFilters",
    "UniverseFilters",
    # Financial Datasets
    "BalanceSheetData",
    "FinancialDatasetsPackage",
    "FinancialMetricsData",
    "IncomeStatementData",
    # History
    "HistoryPoint",
    "TrendingTicker",
    # Health
    "HealthStatus",
    # Intelligence
    "AnalystActivitySnapshot",
    "AnalystSnapshot",
    "InsiderSnapshot",
    "InsiderTransaction",
    "InstitutionalSnapshot",
    "IntelligencePackage",
    "UpgradeDowngrade",
    # Metadata
    "MetadataCoverage",
    "TickerMetadata",
    # Valuation
    "CompositeValuation",
    "ValuationModelResult",
    # Audit
    "AuditFinding",
    "AuditLayerSummary",
    "AuditReport",
    # Correlation
    "CorrelationMatrix",
    "PairwiseCorrelation",
]
